### PR TITLE
Updated all dependencies + yarn v3

### PR DESCRIPTION
**Pull request by doronnac**
Tests pass

### CODE REVIEW

**Comment by insidewhy** [comment]
Don't think the yarn cache should be part of the repo, also could you update the commit messages to be in imperative mood for consistency with the rest of the commit messages.

**Comment by doronnac** [comment]
Please check now

**Comment by insidewhy** [comment]
Thanks, but rather than adding a lot of data and removing it in a subsequent commit, could you edit the previous commit so that the data was never added in the first place. I don't want to make a merge which will unnecessarily increase the size of the git repo by several times.

**Comment by doronnac** [comment]
Good point, I'll do it tomorrow

**Comment by doronnac** [comment]
Done, conflicts most likely due to the latest forcible history change, not really sure why but it seems fine to me.

**Comment by doronnac** [comment]
Looking more into it, I see that there are indeed trivial conflicts.
You can either resolve the conflicts or I can issue a clean PR, please let me know.

**Pull request closed without merging**
